import { useEffect, useMemo, useState } from 'react'
import { db, nowIso } from '../db'
import type { Inspection, Zone } from '../types'
import { BottomNav } from '../components/BottomNav'

export function ArchivePage(){
  const[zones,setZones]=useState<Zone[]>([]);const[inspections,setInspections]=useState<Inspection[]>([]);const[search,setSearch]=useState('');const[zoneId,setZoneId]=useState(()=>new URLSearchParams(location.hash.split('?')[1]||'').get('zone')||'');const[sort,setSort]=useState('recent')
  const load=async()=>{setZones(await db.zones.orderBy('name').toArray());setInspections((await db.inspections.toArray()).filter(i=>!(i as any).deletedAt))}
  useEffect(()=>{load()},[])
  const zoneMap=useMemo(()=>Object.fromEntries(zones.map(z=>[z.id,z.name])),[zones])
  const list=useMemo(()=>{let a=inspections.filter(i=>!zoneId||i.zoneId===zoneId).filter(i=>`${i.name} ${i.address} ${i.municipality} ${i.province} ${zoneMap[i.zoneId]||''} ${i.data.general?.ownerAgency||''} ${i.data.general?.contact||''}`.toLowerCase().includes(search.toLowerCase()));a=[...a].sort((x,y)=>sort==='score'?((y.score||0)-(x.score||0)):sort==='name'?(x.municipality||x.name).localeCompare(y.municipality||y.name):y.updatedAt.localeCompare(x.updatedAt));return a},[inspections,zoneId,search,sort,zoneMap])
  const counts=useMemo(()=>zones.map(z=>({z,count:inspections.filter(i=>i.zoneId===z.id).length})),[zones,inspections])
  if(!zoneId)return <div className="app-shell"><main className="page"><header className="topbar"><div><div className="eyebrow">Sviluppo Filiali</div><h1>Archivio</h1></div><button className="btn primary small" onClick={()=>location.hash='#/new'}>+ Nuovo</button></header><div className="searchbar"><span>⌕</span><input placeholder="Cerca indirizzo, Comune, zona..." value={search} onChange={e=>setSearch(e.target.value)}/></div><section className="section-block"><div className="card-heading"><h2>Zone</h2></div><div className="zone-list">{counts.filter(x=>x.z.name.toLowerCase().includes(search.toLowerCase())).map(({z,count})=><button className="zone-row" key={z.id} onClick={()=>setZoneId(z.id)}><div><strong>{z.name}</strong><span>{[z.region,z.provinces?.join(', ')].filter(Boolean).join(' · ')}</span></div><b>{count}</b></button>)}{!zones.length&&<div className="empty-state">Nessuna zona creata.</div>}</div></section><section className="section-block"><button className="btn ghost wide" onClick={()=>location.hash='#/trash'}>Cestino</button></section></main><BottomNav active="archive"/></div>
  const zone=zones.find(z=>z.id===zoneId)
  return <div className="app-shell"><main className="page"><header className="topbar"><button className="back-btn" onClick={()=>setZoneId('')}>←</button><div><div className="eyebrow">Archivio zona</div><h1>{zone?.name||'Zona'}</h1></div></header><section className="dashboard-card"><div className="stats"><div><strong>{list.length}</strong><span>Capannoni</span></div><div><strong>{Math.round(list.reduce((s,i)=>s+(i.score||0),0)/(list.filter(i=>i.score!=null).length||1))}</strong><span>Punteggio medio</span></div><div><strong>{list.filter(i=>['Interessante','Molto interessante'].includes(i.judgment||'')).length}</strong><span>Interessanti</span></div><div><strong>{list.filter(i=>i.blockingIssues?.length).length}</strong><span>Bloccanti</span></div></div></section><div className="archive-controls"><div className="searchbar"><span>⌕</span><input placeholder="Cerca..." value={search} onChange={e=>setSearch(e.target.value)}/></div><select value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Più recenti</option><option value="score">Punteggio più alto</option><option value="name">Comune A–Z</option></select></div><div className="archive-grid">{list.map(i=><InspectionArchiveCard key={i.id} i={i} zoneName={zone?.name||''} onDelete={async()=>{if(confirm('Spostare questo sopralluogo nel cestino?')){await db.inspections.update(i.id,{deletedAt:nowIso()} as any);load()}}}/>)}{!list.length&&<div className="empty-state">Nessun capannone corrisponde ai filtri.</div>}</div></main><BottomNav active="archive"/></div>
}

function InspectionArchiveCard({i,zoneName,onDelete}:{i:Inspection;zoneName:string;onDelete:()=>void}){const d=i.data||{};return <article className="archive-card"><button className="archive-card-main" onClick={()=>location.hash=`#/inspection/${i.id}/general`}><div className="archive-thumb">⌂</div><div className="archive-body"><div className="archive-title"><strong>{i.name||i.address}</strong>{i.blockingIssues?.length?<span className="warning-pill">⚠</span>:null}</div><span>{zoneName} · {new Date(i.date).toLocaleDateString('it-IT')}</span><div className="archive-metrics"><span>{d.warehouse?.coveredArea||d.general?.declaredCoveredArea||'—'} m² coperti</span><span>{d.yard?.yardArea||d.general?.declaredYardArea||'—'} m² piazzale</span><span>{d.yard?.usableYardArea||'—'} m² utilizzabili</span></div></div><div className="archive-score"><strong>{i.score??'—'}</strong><span>{i.score!=null?'/100':'Bozza'}</span><small>{i.judgment||i.classification||''}</small></div></button><div className="archive-actions"><button onClick={()=>location.hash=`#/rapid/${i.id}`}>Rapido</button><button onClick={()=>location.hash=`#/share/${i.id}`}>Email</button><button onClick={()=>location.hash=`#/map?inspection=${i.id}`}>Maps</button><button className="danger" onClick={onDelete}>Elimina</button></div></article>}

export function TrashPage(){const[list,setList]=useState<Inspection[]>([]);const load=()=>db.inspections.toArray().then(x=>setList(x.filter(i=>(i as any).deletedAt)));useEffect(()=>{load()},[]);return <div className="page"><header className="topbar"><button className="back-btn" onClick={()=>history.back()}>←</button><div><div className="eyebrow">Archivio</div><h1>Cestino</h1></div></header><div className="list-stack">{list.map(i=><div className="list-row" key={i.id}><div><strong>{i.name}</strong><div className="muted">{i.address}</div></div><div className="row-actions"><button className="btn secondary small" onClick={async()=>{await db.inspections.update(i.id,{deletedAt:undefined} as any);load()}}>Ripristina</button><button className="btn danger small" onClick={async()=>{if(confirm('Eliminare definitivamente sopralluogo, foto e documenti?')){await db.transaction('rw',[db.inspections,db.photos,db.documents],async()=>{await db.photos.where('inspectionId').equals(i.id).delete();await db.documents.where('inspectionId').equals(i.id).delete();await db.inspections.delete(i.id)});load()}}}>Definitivo</button></div></div>)}{!list.length&&<div className="empty-state">Il cestino è vuoto.</div>}</div></div>}
