import { useEffect, useState } from 'react'
import { db, setSetting } from '../db'
import type { Zone } from '../types'
import { createBackup, downloadBlob, inspectBackup, restoreBackup } from '../services/backup'

export function BackupPage(){const[zones,setZones]=useState<Zone[]>([]);const[stats,setStats]=useState({inspections:0,photos:0,docs:0});const[busy,setBusy]=useState(false);const[info,setInfo]=useState<any>(null);const[protect,setProtect]=useState(false);const[password,setPassword]=useState('');const[conflict,setConflict]=useState<'current'|'backup'|'both'>('current')
  const load=async()=>{setZones(await db.zones.toArray());setStats({inspections:await db.inspections.count(),photos:await db.photos.count(),docs:await db.documents.count()})};useEffect(()=>{load()},[])
  const backup=async(zoneId?:string)=>{setBusy(true);try{if(protect&&!password)return alert('Inserisci una password per proteggere il backup.');const b=await createBackup(zoneId,protect?password:undefined);const zone=zones.find(z=>z.id===zoneId);const date=new Date().toISOString().slice(0,10);downloadBlob(b,zone?`SviluppoFiliali_${zone.name.replaceAll(' ','_')}_${date}.sfbackup`:`SviluppoFiliali_Backup_${date}.sfbackup`);await setSetting('lastBackup',new Date().toISOString());alert('Backup creato e verificato.') }finally{setBusy(false)}}
  const inspect=async(f:File)=>{let pw='';try{let x;try{x=await inspectBackup(f)}catch(e:any){if(e.message==='PASSWORD_REQUIRED'){pw=prompt('Backup protetto. Inserisci password:')||'';x=await inspectBackup(f,pw)}else throw e}const existing=new Set((await db.inspections.toArray()).map(i=>i.id));const full=await inspectBackup(f,pw);const conflicts=(full.data.inspections||[]).filter((i:any)=>existing.has(i.id)).length;setInfo({...x.manifest,file:f,password:pw,conflicts})}catch(e:any){alert(e.message)}}
  return <div className="page narrow-page"><header className="topbar"><button className="back-btn" onClick={()=>history.back()}>←</button><div><div className="eyebrow">Sviluppo Filiali</div><h1>Backup e ripristino</h1></div></header><section className="dashboard-card"><div className="stats"><div><strong>{zones.length}</strong><span>Zone</span></div><div><strong>{stats.inspections}</strong><span>Sopralluoghi</span></div><div><strong>{stats.photos}</strong><span>Foto</span></div><div><strong>{stats.docs}</strong><span>Documenti</span></div></div></section><section className="card"><h3>Backup completo</h3><p className="muted">Include dati, foto, documenti, impostazioni e filiali Mollo.</p><label className="toggle-row"><span>Proteggi backup con password</span><input type="checkbox" checked={protect} onChange={e=>setProtect(e.target.checked)}/></label>{protect&&<div className="field-block"><label>Password backup</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></div>}<button className="btn primary wide" disabled={busy} onClick={()=>backup()}>{busy?'Creazione…':'Crea backup completo'}</button></section><section className="card"><h3>Esporta singola zona</h3><div className="list-stack">{zones.map(z=><div className="list-row" key={z.id}><strong>{z.name}</strong><button className="btn secondary small" disabled={busy} onClick={()=>backup(z.id)}>Esporta</button></div>)}</div></section><section className="card"><h3>Importa backup</h3><label className="btn secondary wide file-btn">Seleziona file .sfbackup<input hidden type="file" accept=".sfbackup,.zip,application/zip" onChange={e=>e.target.files?.[0]&&inspect(e.target.files[0])}/></label>{info&&<div className="backup-info"><strong>Backup del {new Date(info.createdAt).toLocaleString('it-IT')}</strong><span>{info.counts?.zones||0} zone · {info.counts?.inspections||0} sopralluoghi · {info.counts?.photos||0} foto · {info.counts?.documents||0} documenti</span>{info.conflicts>0&&<><div className="field-block"><label>Conflitti ({info.conflicts} sopralluoghi già presenti)</label><select value={conflict} onChange={e=>setConflict(e.target.value as any)}><option value="current">Mantieni versione attuale</option><option value="backup">Usa versione backup</option><option value="both">Mantieni entrambe</option></select></div></>}<div className="button-pair"><button className="btn secondary" onClick={async()=>{setBusy(true);try{await restoreBackup(info.file,'merge',info.password,conflict);alert('Backup unito all’archivio.');await load();setInfo(null)}finally{setBusy(false)}}}>Unisci</button><button className="btn danger" onClick={async()=>{if(confirm('Sostituire completamente l’archivio attuale?')){setBusy(true);try{await restoreBackup(info.file,'replace',info.password,'backup');alert('Archivio ripristinato.');await load();setInfo(null)}finally{setBusy(false)}}}}>Sostituisci</button></div></div>}</section></div>}
