import { useEffect, useMemo, useState } from 'react'
import { db, getSetting } from '../db'
import type { Inspection, Zone } from '../types'
import { BottomNav } from '../components/BottomNav'

export function HomePage(){
  const [inspections,setInspections]=useState<Inspection[]>([]);const[zones,setZones]=useState<Zone[]>([]);const[lastBackup,setLastBackup]=useState<string>('Mai');const[online,setOnline]=useState(navigator.onLine)
  const load=async()=>{setInspections(await db.inspections.orderBy('updatedAt').reverse().toArray());setZones(await db.zones.toArray());setLastBackup(await getSetting('lastBackup','Mai'))}
  useEffect(()=>{load();const f=()=>setOnline(navigator.onLine);window.addEventListener('online',f);window.addEventListener('offline',f);return()=>{window.removeEventListener('online',f);window.removeEventListener('offline',f)}},[])
  const zoneMap=useMemo(()=>Object.fromEntries(zones.map(z=>[z.id,z.name])),[zones]);const completed=inspections.filter(i=>i.status==='completed');const interesting=completed.filter(i=>['Interessante','Molto interessante'].includes(i.judgment||''));const blocking=completed.filter(i=>i.blockingIssues?.length).length
  return <div className="app-shell"><main className="page home-page"><header className="topbar"><div><div className="eyebrow">Sviluppo immobiliare</div><h1>Sviluppo Filiali</h1></div><span className={`status-dot ${online?'online':'offline'}`}>{online?'Online':'Offline'}</span></header>
    <button className="new-inspection" onClick={()=>location.hash='#/new'}><span>＋</span><div><strong>Nuovo sopralluogo</strong><small>Avvia una nuova scheda sul campo</small></div></button>
    <div className="quick-grid"><button className="quick-card" onClick={()=>location.hash='#/archive'}><span>▤</span><strong>Archivio</strong><small>Capannoni visitati</small></button><button className="quick-card" onClick={()=>location.hash='#/map'}><span>⌖</span><strong>Mappa</strong><small>Vista geografica</small></button><button className="quick-card" onClick={()=>document.getElementById('recent')?.scrollIntoView({behavior:'smooth'})}><span>◷</span><strong>Ultimi</strong><small>Sopralluoghi recenti</small></button><button className="quick-card" onClick={()=>location.hash='#/backup'}><span>⇩</span><strong>Backup</strong><small>{lastBackup==='Mai'?'Nessuna copia':new Date(lastBackup).toLocaleDateString('it-IT')}</small></button></div>
    <section className="dashboard-card"><div className="card-heading"><h2>Riepilogo</h2></div><div className="stats"><div><strong>{zones.length}</strong><span>Zone</span></div><div><strong>{completed.length}</strong><span>Capannoni</span></div><div><strong>{interesting.length}</strong><span>Interessanti</span></div><div><strong>{blocking}</strong><span>Bloccanti</span></div></div></section>
    <section id="recent" className="section-block"><div className="card-heading"><h2>Ultimi sopralluoghi</h2><button className="text-btn" onClick={()=>location.hash='#/archive'}>Vedi tutti</button></div><div className="inspection-list">{inspections.slice(0,5).map(i=><button className="inspection-card" key={i.id} onClick={()=>location.hash=`#/inspection/${i.id}/general`}><div className="inspection-avatar">⌂</div><div className="inspection-info"><strong>{i.name||i.address||'Sopralluogo senza nome'}</strong><span>{zoneMap[i.zoneId]||'Zona'} · {new Date(i.date).toLocaleDateString('it-IT')}</span></div><div className="inspection-score">{i.score!=null?<><strong>{i.score}</strong><span>/100</span></>:<span>Bozza</span>}</div></button>)}{!inspections.length&&<div className="empty-state">Nessun sopralluogo. Premi “Nuovo sopralluogo” per iniziare.</div>}</div></section>
    <section className="section-block"><div className="card-heading"><h2>Zone recenti</h2></div><div className="zone-strip">{zones.slice(-3).reverse().map(z=>{const count=inspections.filter(i=>i.zoneId===z.id).length;return <button key={z.id} onClick={()=>location.hash=`#/archive?zone=${z.id}`}><strong>{z.name}</strong><span>{count} capannoni</span></button>})}</div></section>
  </main><BottomNav active="home"/></div>
}
