import { useEffect, useMemo, useState } from 'react'
import { db, nowIso } from '../db'
import { sections, photoCategories } from '../sections'
import type { Inspection, SectionDef, Zone } from '../types'
import { Field } from '../components/Field'
import { DynamicList } from '../components/DynamicList'
import { PhotoManager } from '../components/PhotoManager'
import { DocumentManager } from '../components/DocumentManager'
import { SectionMenu } from '../components/SectionMenu'
import { LocationPicker } from '../components/LocationPicker'
import { getCurrentPosition, googleMapsUrl, nearestBranch, reverseGeocode } from '../services/geo'
import { deriveConfiguration, evaluateInspection } from '../evaluation'
import { generateFullReportPdf, generateReportPdf } from '../services/report'
import { downloadBlob } from '../services/backup'

export function InspectionPage({id,sectionId}:{id:string;sectionId:string}){
  const[inspection,setInspection]=useState<Inspection|null>(null);const[zone,setZone]=useState<Zone>();const[menu,setMenu]=useState(false);const[picker,setPicker]=useState(false);const[saving,setSaving]=useState(false);const section=sections.find(s=>s.id===sectionId)||sections[0]
  const load=async()=>{const i=await db.inspections.get(id);if(!i)return location.hash='#/home';setInspection(i);setZone(await db.zones.get(i.zoneId))}
  useEffect(()=>{load()},[id]);useEffect(()=>{window.scrollTo({top:0,left:0,behavior:'auto'})},[sectionId])
  const save=async(next:Inspection)=>{setSaving(true);const ev=evaluateInspection(next);const stored={...next,score:ev.score,completeness:ev.completeness,classification:ev.classification,blockingIssues:ev.blockingIssues,strengths:ev.strengths,issues:ev.issues,updatedAt:nowIso()};setInspection(stored);await db.inspections.put(stored);setTimeout(()=>setSaving(false),250)}
  const sectionData=inspection?.data?.[section.id]||{}
  const setField=(key:string,value:any)=>{if(!inspection)return;let next={...inspection,data:{...inspection.data,[section.id]:{...sectionData,[key]:value}}};if(section.id==='general'){if(key==='inspectionDate')next.date=value;if(key==='inspectionName')next.name=value}save(next)}
  const setSectionArray=(key:string,items:any[])=>setField(key,items)
  const currentIndex=sections.findIndex(s=>s.id===section.id)
  const go=(delta:number)=>{const next=sections[currentIndex+delta];if(next)location.hash=`#/inspection/${id}/${next.id}`}
  if(!inspection)return <div className="loading">Caricamento...</div>
  return <div className="inspection-page"><header className="inspection-header"><div className="header-row"><button className="back-btn" onClick={()=>location.hash='#/home'}>←</button><div className="inspection-title"><strong>{inspection.name||inspection.address||'Sopralluogo'}</strong><span>{zone?.name||'Zona'} · {new Date(inspection.date).toLocaleDateString('it-IT')}</span></div><span className="save-state">{saving?'Salvataggio…':'✓ Salvato'}</span></div><div className="section-header"><div><span className="section-number">{currentIndex+1}/15</span><h1>{section.title}</h1></div><button className="btn secondary small" onClick={()=>setMenu(true)}>Sezioni</button></div><div className="progress"><span style={{width:`${Math.round(((currentIndex+1)/15)*100)}%`}}/></div></header>
    <main className="inspection-content">
      {section.special==='general'&&<GeneralGeo inspection={inspection} onSave={save} onPicker={()=>setPicker(true)}/>}      
      {section.cards.map(card=><details className="card collapsible" open key={card.title}><summary><div><h3>{card.title}</h3>{card.description&&<p>{card.description}</p>}</div><span>⌄</span></summary><div className="card-body">{card.fields.map(f=><Field key={f.key} field={f} values={sectionData} onChange={setField}/>)}</div></details>)}
      {section.special==='warehouse'&&<DynamicList title="Portoni" addLabel="Aggiungi portone" items={sectionData.ports||[]} onChange={x=>setSectionArray('ports',x)} columns={[{key:'name',label:'Nome'},{key:'width',label:'Larghezza',type:'number',unit:' m'},{key:'height',label:'Altezza',type:'number',unit:' m'},{key:'type',label:'Tipologia',type:'choice',options:['Sezionale','Scorrevole','A libro','Altro']},{key:'directYard',label:'Accesso diretto al piazzale',type:'choice',options:['Sì','No']},{key:'vehicleSuitable',label:'Idoneo al passaggio mezzi',type:'choice',options:['Sì','No','Da verificare']},{key:'notes',label:'Note'}]}/>}      
      {section.special==='access'&&<DynamicList title="Accessi e cancelli" addLabel="Aggiungi accesso" items={sectionData.accesses||[]} onChange={x=>setSectionArray('accesses',x)} columns={[{key:'name',label:'Nome / identificativo'},{key:'width',label:'Larghezza',type:'number',unit:' m'},{key:'height',label:'Altezza utile',type:'number',unit:' m'},{key:'opening',label:'Apertura',type:'choice',options:['Manuale','Automatica','Altro']},{key:'semiSuitable',label:'Accessibile ai bilici',type:'choice',options:['Sì','No','Da verificare']},{key:'notes',label:'Note'}]}/>}      
      {section.measurements&&<DynamicList title="Misure aggiuntive" addLabel="Aggiungi misura" items={sectionData.measurements||[]} onChange={x=>setSectionArray('measurements',x)} columns={[{key:'name',label:'Nome misura'},{key:'value',label:'Valore',type:'number'},{key:'unit',label:'Unità'},{key:'note',label:'Nota'}]}/>}      
      {section.special==='systems'&&<DynamicList title="Dati aggiuntivi" addLabel="Aggiungi dato" items={sectionData.extraData||[]} onChange={x=>setSectionArray('extraData',x)} columns={[{key:'name',label:'Nome'},{key:'value',label:'Valore'},{key:'unit',label:'Unità'},{key:'note',label:'Nota'}]}/>}      
      {section.special==='planning'&&<DynamicList title="Verifiche da approfondire" addLabel="Aggiungi verifica" items={sectionData.checks||[]} onChange={x=>setSectionArray('checks',x)} columns={[{key:'name',label:'Titolo'},{key:'status',label:'Stato',type:'choice',options:['Da verificare','Verificato']},{key:'note',label:'Note'}]}/>}      
      {section.special==='location'&&<LocationExtras inspection={inspection} values={sectionData} setArray={setSectionArray}/>}      
      {section.special==='configuration'&&<ConfigurationPanel inspection={inspection} onChange={setField}/>}      
      {section.special==='photos'&&<PhotoLibrary inspectionId={inspection.id}/>}      
      {section.special==='documents'&&<DocumentManager inspection={inspection} onInspectionChange={save}/>}      
      {section.special==='evaluation'&&<EvaluationPanel inspection={inspection} zone={zone} onSave={save}/>}      
      {section.photoCategory&&<><PhotoManager inspectionId={inspection.id} category={section.photoCategory}/>{section.id==='yard'&&sectionData.overheadPowerLines==='Sì'&&<PhotoManager inspectionId={inspection.id} category="Cavi elettrici aerei"/>}</>}
    </main>
    <footer className="inspection-footer"><button className="btn secondary" disabled={currentIndex===0} onClick={()=>go(-1)}>← Precedente</button>{currentIndex<sections.length-1?<button className="btn primary" onClick={()=>go(1)}>{sections[currentIndex+1].shortTitle} →</button>:<button className="btn primary" onClick={()=>location.hash='#/home'}>Chiudi</button>}</footer>
    {menu&&<SectionMenu inspectionId={id} current={section.id} onClose={()=>setMenu(false)}/>}    
    {picker&&<LocationPicker lat={inspection.lat} lng={inspection.lng} onClose={()=>setPicker(false)} onConfirm={async(lat,lng)=>{setPicker(false);const r=await reverseGeocode(lat,lng);await save({...inspection,lat,lng,address:r?.address||inspection.address,municipality:r?.municipality||inspection.municipality,province:r?.province||inspection.province,postalCode:r?.postalCode||inspection.postalCode,name:r?.municipality&&r?.address?`${r.municipality} – ${r.address}`:inspection.name})}}/>}
  </div>
}

function GeneralGeo({inspection,onSave,onPicker}:{inspection:Inspection;onSave:(i:Inspection)=>void;onPicker:()=>void}){
  const[busy,setBusy]=useState(false)
  const patch=(p:Partial<Inspection>)=>onSave({...inspection,...p})
  const gps=async()=>{setBusy(true);try{const pos=await getCurrentPosition();const lat=pos.coords.latitude,lng=pos.coords.longitude,r=await reverseGeocode(lat,lng);patch({lat,lng,address:r?.address||inspection.address,municipality:r?.municipality||inspection.municipality,province:r?.province||inspection.province,postalCode:r?.postalCode||inspection.postalCode,name:r?.municipality&&r?.address?`${r.municipality} – ${r.address}`:inspection.name})}catch(e:any){alert(e.message||'GPS non disponibile')}finally{setBusy(false)}}
  return <section className="card"><div className="card-heading"><div><h3>Posizione</h3><div className="muted small-text">GPS automatico o selezione manuale sulla mappa.</div></div></div><div className="button-pair"><button className="btn primary" onClick={gps} disabled={busy}>{busy?'Rilevamento…':'Rileva GPS'}</button><button className="btn secondary" onClick={onPicker}>Seleziona sulla mappa</button></div>
    <div className="field-block"><label>Indirizzo completo</label><input value={inspection.address||''} onChange={e=>patch({address:e.target.value})}/></div><div className="two-col"><div className="field-block"><label>Comune</label><input value={inspection.municipality||''} onChange={e=>patch({municipality:e.target.value})}/></div><div className="field-block"><label>Provincia</label><input value={inspection.province||''} onChange={e=>patch({province:e.target.value})}/></div><div className="field-block"><label>CAP</label><input value={inspection.postalCode||''} onChange={e=>patch({postalCode:e.target.value})}/></div><div className="field-block"><label>Coordinate</label><input readOnly value={inspection.lat!=null?`${inspection.lat.toFixed(6)}, ${inspection.lng?.toFixed(6)}`:''}/></div></div><button className="btn ghost wide" disabled={!inspection.address&&inspection.lat==null} onClick={()=>window.open(googleMapsUrl(inspection.lat,inspection.lng,inspection.address),'_blank')}>Apri in Google Maps</button></section>
}

function LocationExtras({inspection,values,setArray}:{inspection:Inspection;values:Record<string,any>;setArray:(k:string,v:any[])=>void}){
  const[nearest,setNearest]=useState<any>(null)
  useEffect(()=>{db.branches.toArray().then(b=>setNearest(nearestBranch(inspection.lat,inspection.lng,b)))},[inspection.lat,inspection.lng])
  return <><DynamicList title="Competitor" addLabel="Aggiungi competitor" items={values.competitors||[]} onChange={x=>setArray('competitors',x)} columns={[{key:'name',label:'Nome'},{key:'address',label:'Indirizzo / posizione'},{key:'distance',label:'Distanza indicativa',type:'number',unit:' km'},{key:'note',label:'Note'}]}/><section className="card nearest-card"><h3>Filiale Mollo più vicina</h3>{nearest?<><strong>{nearest.branch.name}</strong><span>{nearest.branch.municipality}{nearest.branch.province?` (${nearest.branch.province})`:''}</span><div className="nearest-distance">{nearest.distanceKm.toFixed(1)} km <small>distanza geografica</small></div><button className="btn secondary" onClick={()=>window.open(googleMapsUrl(nearest.branch.lat,nearest.branch.lng,nearest.branch.address),'_blank')}>Apri in Google Maps</button></>:<div className="empty-inline">Nessuna filiale con coordinate nell’archivio locale. Importa l’elenco dalle Impostazioni.</div>}</section><DynamicList title="Dati aggiuntivi" addLabel="Aggiungi dato" items={values.extraData||[]} onChange={x=>setArray('extraData',x)} columns={[{key:'name',label:'Dato'},{key:'value',label:'Valore'},{key:'note',label:'Nota'}]}/></>
}

function ConfigurationPanel({inspection,onChange}:{inspection:Inspection;onChange:(k:string,v:any)=>void}){
  const cfg=deriveConfiguration(inspection);const rows=[['Deposito mezzi',cfg.vehicleStorage],['Piazzale operativo',cfg.operationalYard],['Area officina',cfg.workshop],['Reception / area clienti',cfg.reception],['Uffici e servizi',cfg.offices],['Area lavaggio',cfg.wash],['Area rifornimento',cfg.fuel],['Parcheggi',cfg.parking],['Impianti',cfg.systems],['Compatibilità urbanistica',cfg.planning]]
  const ev=evaluateInspection(inspection)
  return <div className="stack"><section className="card"><h3>Sintesi automatica</h3><div className="config-grid">{rows.map(([k,v])=><div className="config-row" key={k}><span>{k}</span><strong>{v}</strong></div>)}</div></section><section className="card"><h3>Criticità rilevate</h3>{ev.issues.length?ev.issues.map(x=><div className="issue-row" key={x}>⚠ {x}</div>):<div className="empty-inline">Nessuna criticità automatica rilevata.</div>}</section><section className="card"><h3>Configurazione Mollo</h3><div className={`overall-badge ${cfg.overall.toLowerCase().replaceAll(' ','-')}`}>{cfg.overall}</div><div className="field-block"><label>Valutazione personale layout</label><div className="chips">{['Confermo valutazione automatica','Migliore del risultato automatico','Peggiore del risultato automatico'].map(o=><button className={`chip ${inspection.data.configuration?.layoutOverride===o?'selected':''}`} key={o} onClick={()=>onChange('layoutOverride',o)}>{o}</button>)}</div></div><div className="field-block"><label>Note configurazione filiale</label><textarea rows={4} value={inspection.data.configuration?.configurationNotes||''} onChange={e=>onChange('configurationNotes',e.target.value)}/></div></section></div>
}

function PhotoLibrary({inspectionId}:{inspectionId:string}){const[cat,setCat]=useState(photoCategories[0]);return <div className="stack"><section className="card"><h3>Categorie foto</h3><div className="category-grid">{photoCategories.map(c=><button key={c} className={cat===c?'active':''} onClick={()=>setCat(c)}>{c}</button>)}</div></section><PhotoManager inspectionId={inspectionId} category={cat}/></div>}

function EvaluationPanel({inspection,zone,onSave}:{inspection:Inspection;zone?:Zone;onSave:(i:Inspection)=>void}){
  const ev=useMemo(()=>evaluateInspection(inspection),[inspection]);const cfg=deriveConfiguration(inspection);const[working,setWorking]=useState(false)
  const judgmentOptions=['Molto interessante','Interessante','Da approfondire','Poco interessante','Non idoneo'] as const
  const updateEval=(p:any)=>onSave({...inspection,data:{...inspection.data,evaluation:{...(inspection.data.evaluation||{}),...p}}})
  const pdf=async()=>{setWorking(true);try{const blob=await generateReportPdf(inspection,zone);downloadBlob(blob,`Scheda_Tecnica_${(inspection.municipality||'capannone').replaceAll(' ','_')}_${inspection.date}.pdf`)}finally{setWorking(false)}};const fullPdf=async()=>{setWorking(true);try{const blob=await generateFullReportPdf(inspection,zone);downloadBlob(blob,`Report_Completo_${(inspection.municipality||'capannone').replaceAll(' ','_')}_${inspection.date}.pdf`)}finally{setWorking(false)}}
  const complete=async()=>{await onSave({...inspection,status:'completed'});location.hash='#/home'}
  return <div className="stack"><section className="score-hero"><div><strong>{ev.score}</strong><span>/100</span></div><h2>{ev.classification}</h2><p>Completezza dati: <b>{ev.completeness}%</b></p>{ev.blockingIssues.length>0&&<div className="blocking-banner">⚠ Criticità bloccante presente</div>}</section><section className="card"><h3>Configurazione Mollo</h3><div className="config-grid">{Object.entries({Piazzale:cfg.operationalYard,'Deposito mezzi':cfg.vehicleStorage,'Area officina':cfg.workshop,Reception:cfg.reception,Lavaggio:cfg.wash,Rifornimento:cfg.fuel,Urbanistica:cfg.planning}).map(([k,v])=><div className="config-row" key={k}><span>{k}</span><strong>{v}</strong></div>)}</div></section><section className="card split-card"><div><h3>Punti di forza</h3>{ev.strengths.map(s=><div className="strength-row" key={s}>+ {s}</div>)}{!ev.strengths.length&&<div className="empty-inline">Nessuno ancora identificato.</div>}</div><div><h3>Criticità</h3>{[...ev.blockingIssues,...ev.issues].slice(0,5).map(s=><div className="issue-row" key={s}>⚠ {s}</div>)}{!ev.issues.length&&!ev.blockingIssues.length&&<div className="empty-inline">Nessuna criticità rilevata.</div>}</div></section><section className="card"><h3>Giudizio personale</h3><div className="chips vertical-mobile">{judgmentOptions.map(o=><button className={`chip ${inspection.judgment===o?'selected':''}`} key={o} onClick={()=>onSave({...inspection,judgment:o})}>{o}</button>)}</div><div className="field-block"><label>Considerazioni finali</label><textarea rows={5} value={inspection.data.evaluation?.finalNotes||''} onChange={e=>updateEval({finalNotes:e.target.value})}/></div></section><div className="final-actions"><button className="btn primary big" disabled={working} onClick={pdf}>{working?'Generazione…':'Scheda tecnica sintetica PDF'}</button><button className="btn secondary big" disabled={working} onClick={fullPdf}>Report completo PDF</button><button className="btn secondary" onClick={()=>location.hash=`#/share/${inspection.id}?type=full`}>Email / Condividi report completo</button><button className="btn ghost" onClick={()=>location.hash=`#/rapid/${inspection.id}`}>Riapri sopralluogo rapido</button><button className="btn success" onClick={complete}>Salva e chiudi sopralluogo</button></div></div>
}
