import { useEffect, useRef, useState } from 'react'
import L from 'leaflet'
import { db } from '../db'
import type { Inspection, Zone } from '../types'
import { BottomNav } from '../components/BottomNav'
import { googleMapsUrl } from '../services/geo'

export function MapPage(){const ref=useRef<HTMLDivElement>(null);const[inspections,setInspections]=useState<Inspection[]>([]);const[zones,setZones]=useState<Zone[]>([]);const[zoneId,setZoneId]=useState('');const[selected,setSelected]=useState<Inspection|null>(null)
  useEffect(()=>{Promise.all([db.inspections.toArray(),db.zones.toArray()]).then(([i,z])=>{setInspections(i.filter(x=>!(x as any).deletedAt&&x.lat!=null&&x.lng!=null));setZones(z)})},[])
  useEffect(()=>{if(!ref.current||!inspections.length)return;const visible=inspections.filter(i=>!zoneId||i.zoneId===zoneId);if(!visible.length)return;const center:[number,number]=[visible[0].lat!,visible[0].lng!];const map=L.map(ref.current).setView(center,8);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);const group=L.featureGroup().addTo(map);visible.forEach(i=>{const marker=L.circleMarker([i.lat!,i.lng!],{radius:9,color:i.blockingIssues?.length?'#b91c1c':'#0f766e',fillColor:i.judgment==='Non idoneo'?'#ef4444':'#14b8a6',fillOpacity:.85}).addTo(group);marker.bindTooltip(i.name||i.address);marker.on('click',()=>setSelected(i))});if(visible.length>1)map.fitBounds(group.getBounds().pad(.15));map.on('contextmenu',(e:L.LeafletMouseEvent)=>{if(confirm('Creare un nuovo sopralluogo in questo punto?')){sessionStorage.setItem('sf-new-point',JSON.stringify({lat:e.latlng.lat,lng:e.latlng.lng,zoneId}));location.hash='#/new'}});setTimeout(()=>map.invalidateSize(),50);return()=>map.remove()},[inspections,zoneId])
  return <div className="app-shell map-page"><header className="map-top"><div><div className="eyebrow">Sviluppo Filiali</div><h1>Mappa</h1></div><select value={zoneId} onChange={e=>setZoneId(e.target.value)}><option value="">Tutte le zone</option>{zones.map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</select></header>{inspections.length?<div ref={ref} className="full-map"/>:<div className="empty-state map-empty">Nessun sopralluogo con coordinate GPS.</div>}{selected&&<div className="map-sheet"><button className="sheet-close" onClick={()=>setSelected(null)}>×</button><strong>{selected.name}</strong><span>{selected.address}</span><div className="score-inline"><b>{selected.score??'—'}/100</b> {selected.judgment||selected.classification}</div><div className="button-pair"><button className="btn primary" onClick={()=>location.hash=`#/inspection/${selected.id}/general`}>Apri scheda</button><button className="btn secondary" onClick={()=>window.open(googleMapsUrl(selected.lat,selected.lng,selected.address),'_blank')}>Naviga</button></div></div>}<BottomNav active="map"/></div>}
