import { useEffect, useMemo, useState } from 'react'
import { db, nowIso, uid } from '../db'
import type { Inspection, PhotoRecord, Zone } from '../types'
import { getCurrentPosition, googleMapsUrl, reverseGeocode } from '../services/geo'
import { LocationPicker } from '../components/LocationPicker'
import { DynamicList } from '../components/DynamicList'
import { evaluateInspection } from '../evaluation'
import { rapidCompleteness } from '../services/rapid'
import { generateRapidReportPdf } from '../services/report'
import { downloadBlob } from '../services/backup'

const judgementOptions=['Molto interessante','Interessante','Da approfondire','Poco interessante','Non idoneo'] as const
const photoButtons=[
  ['Esterno','Esterno'],['Piazzale','Piazzale'],['Interno','Capannone'],['Uffici','Uffici e servizi'],['Criticità','Criticità'],['Altro','Altro']
] as const

export function RapidInspectionPage({id}:{id:string}){
  const[inspection,setInspection]=useState<Inspection|null>(null);const[zone,setZone]=useState<Zone>();const[picker,setPicker]=useState(false);const[saving,setSaving]=useState(false);const[working,setWorking]=useState(false);const[photoTick,setPhotoTick]=useState(0)
  useEffect(()=>{(async()=>{const i=await db.inspections.get(id);if(!i)return location.hash='#/home';setInspection(i);setZone(await db.zones.get(i.zoneId));window.scrollTo(0,0)})()},[id])
  const persist=(transform:(i:Inspection)=>Inspection)=>{setInspection(prev=>{if(!prev)return prev;const next=transform(prev),ev=evaluateInspection(next);const stored={...next,score:ev.score,completeness:ev.completeness,classification:ev.classification,blockingIssues:ev.blockingIssues,strengths:ev.strengths,issues:ev.issues,updatedAt:nowIso()};setSaving(true);db.inspections.put(stored).finally(()=>setTimeout(()=>setSaving(false),220));return stored})}
  const sectionField=(section:string,key:string,value:any)=>persist(i=>({...i,data:{...i.data,[section]:{...(i.data?.[section]||{}),[key]:value}}}))
  const topPatch=(p:Partial<Inspection>)=>persist(i=>({...i,...p}))
  const rapidField=(key:string,value:any)=>sectionField('rapid',key,value)
  const setPort=(index:number,key:string,value:any)=>persist(i=>{const w=i.data?.warehouse||{},ports=[...(w.ports||[])];ports[index]={...(ports[index]||{name:index===0?'Principale':`Portone ${index+1}`}),[key]:value};return {...i,data:{...i.data,warehouse:{...w,ports}}}})
  const setMainAccess=(key:string,value:any)=>persist(i=>{const a=i.data?.access||{},accesses=[...(a.accesses||[])];accesses[0]={...(accesses[0]||{name:'Principale'}),[key]:value};return {...i,data:{...i.data,access:{...a,accesses}}}})
  const completeLive=async(goFull=false)=>{if(!inspection)return;const rapid={...(inspection.data?.rapid||{}),liveCompletedAt:nowIso(),liveCompleteness:rapidCompleteness(inspection)};const next={...inspection,status:'completed' as const,data:{...inspection.data,rapid},updatedAt:nowIso()};const ev=evaluateInspection(next);await db.inspections.put({...next,score:ev.score,completeness:ev.completeness,classification:ev.classification,blockingIssues:ev.blockingIssues,strengths:ev.strengths,issues:ev.issues});if(goFull){location.hash=`#/inspection/${id}/general`}else location.hash='#/home'}
  const pdf=async()=>{if(!inspection)return;setWorking(true);try{const blob=await generateRapidReportPdf(inspection,zone);downloadBlob(blob,`Sopralluogo_Rapido_${safeName(inspection)}_${inspection.date}.pdf`)}finally{setWorking(false)}}
  if(!inspection)return <div className="loading">Caricamento...</div>
  const d=inspection.data||{},g=d.general||{},w=d.warehouse||{},y=d.yard||{},a=d.access||{},o=d.offices||{},ws=d.workshop||{},wash=d.wash||{},fuel=d.fuel||{},s=d.systems||{},rapid=d.rapid||{},mainPort=(w.ports||[])[0]||{},mainAccess=(a.accesses||[])[0]||{}
  const live=rapidCompleteness(inspection)
  return <div className="rapid-page"><header className="rapid-header"><div className="header-row"><button className="back-btn" onClick={()=>location.hash='#/home'}>←</button><div className="inspection-title"><strong>{inspection.name||inspection.address||'Sopralluogo rapido'}</strong><span>{zone?.name||'Zona'} · {new Date(inspection.date).toLocaleDateString('it-IT')}</span></div><span className="save-state">{saving?'Salvataggio…':'✓ Salvato'}</span></div><div className="rapid-progress"><span style={{width:`${live}%`}}/><b>{live}% live</b></div></header>
    <main className="rapid-content">
      <RapidCard n="1" title="Identificazione"><div className="button-pair"><button className="btn primary" onClick={async()=>{try{const p=await getCurrentPosition();const lat=p.coords.latitude,lng=p.coords.longitude,r=await reverseGeocode(lat,lng);topPatch({lat,lng,address:r?.address||inspection.address,municipality:r?.municipality||inspection.municipality,province:r?.province||inspection.province,postalCode:r?.postalCode||inspection.postalCode,name:r?.municipality&&r?.address?`${r.municipality} – ${r.address}`:inspection.name})}catch(e:any){alert(e.message||'GPS non disponibile')}}}>Rileva GPS</button><button className="btn secondary" onClick={()=>setPicker(true)}>Correggi posizione</button></div><div className="rapid-location"><strong>{inspection.address||'Indirizzo da rilevare'}</strong><span>{[inspection.postalCode,inspection.municipality,inspection.province].filter(Boolean).join(' · ')}</span></div></RapidCard>

      <RapidCard n="2" title="Dati economici"><QuickChoice label="Operazione" value={g.availabilityType} options={['Solo locazione','Solo vendita','Locazione o vendita','Da verificare']} onChange={v=>sectionField('general','availabilityType',v)}/><div className="two-col"><Num label="Canone" value={g.rent} unit="€/mese" onChange={v=>sectionField('general','rent',v)}/><Num label="Prezzo" value={g.salePrice} unit="€" onChange={v=>sectionField('general','salePrice',v)}/><Text label="Spese" value={g.additionalCosts} onChange={v=>sectionField('general','additionalCosts',v)}/><Text label="Disponibilità" value={g.propertyAvailability} onChange={v=>sectionField('general','propertyAvailability',v)}/></div></RapidCard>

      <RapidCard n="3" title="Misure principali"><div className="rapid-measures"><Num label="Superficie coperta" value={w.coveredArea} unit="m²" onChange={v=>sectionField('warehouse','coveredArea',v)}/><Num label="Piazzale" value={y.yardArea} unit="m²" onChange={v=>sectionField('yard','yardArea',v)}/><Num label="Uffici" value={o.officeArea} unit="m²" onChange={v=>sectionField('offices','officeArea',v)}/><Num label="Altezza sotto trave" value={w.underBeamHeight} unit="m" onChange={v=>sectionField('warehouse','underBeamHeight',v)}/><Num label="Altezza massima" value={w.maxHeight} unit="m" onChange={v=>sectionField('warehouse','maxHeight',v)}/><Num label="Portone principale · larghezza" value={mainPort.width} unit="m" onChange={v=>setPort(0,'width',v)}/><Num label="Portone principale · altezza" value={mainPort.height} unit="m" onChange={v=>setPort(0,'height',v)}/></div><DynamicList title="Misure aggiuntive" addLabel="Aggiungi misura" items={w.measurements||[]} onChange={items=>sectionField('warehouse','measurements',items)} columns={[{key:'name',label:'Misura'},{key:'value',label:'Valore',type:'number'},{key:'unit',label:'Unità'}]}/></RapidCard>

      <RapidCard n="4" title="Accessibilità"><QuickChoice label="Bilici" value={a.semiAccess} options={['Agevole','Possibile','Difficoltoso','Non possibile']} onChange={v=>sectionField('access','semiAccess',v)}/><QuickChoice label="Mezzi pesanti" value={a.heavyAccess} options={['Agevole','Possibile','Difficoltoso','Non possibile']} onChange={v=>sectionField('access','heavyAccess',v)}/><QuickChoice label="Manovra nel piazzale" value={y.truckManeuver} options={['Agevole','Possibile','Difficoltosa','Non possibile']} onChange={v=>sectionField('yard','truckManeuver',v)}/><div className="two-col"><Num label="Accesso principale · larghezza" value={mainAccess.width} unit="m" onChange={v=>setMainAccess('width',v)}/><Num label="Accesso principale · altezza" value={mainAccess.height} unit="m" onChange={v=>setMainAccess('height',v)}/></div><Area label="Problemi accesso / viabilità" value={a.accessNotes} onChange={v=>sectionField('access','accessNotes',v)}/></RapidCard>

      <RapidCard n="5" title="Piazzale"><QuickChoice label="Deposito mezzi" value={y.vehicleStorage} options={['Sì','Parzialmente','No']} onChange={v=>sectionField('yard','vehicleStorage',v)}/><QuickChoice label="Mezzi grandi" value={y.largeVehicles} options={['Sì','No','Da verificare']} onChange={v=>sectionField('yard','largeVehicles',v)}/><QuickChoice label="Pavimentazione" value={y.yardSurfaceState} options={['Buono','Sufficiente','Da sistemare','Critico']} onChange={v=>sectionField('yard','yardSurfaceState',v)}/><QuickChoice label="Recintato" value={y.fenced} options={['Sì','Parzialmente','No']} onChange={v=>sectionField('yard','fenced',v)}/><QuickChoice label="Cavi elettrici aerei" value={y.overheadPowerLines} options={['No','Sì','Da verificare']} onChange={v=>sectionField('yard','overheadPowerLines',v)}/></RapidCard>

      <RapidCard n="6" title="Capannone"><QuickChoice label="Movimentazione interna" value={w.internalMovement} options={['Agevole','Possibile','Difficoltosa','Critica']} onChange={v=>sectionField('warehouse','internalMovement',v)}/><QuickChoice label="Pilastri interferenti" value={w.columnInterference} options={['No','Parzialmente','Sì']} onChange={v=>sectionField('warehouse','columnInterference',v)}/><QuickChoice label="Pavimento" value={w.floorState} options={['Buono','Sufficiente','Da sistemare','Critico']} onChange={v=>sectionField('warehouse','floorState',v)}/><QuickChoice label="Copertura" value={w.roofState} options={['Buono','Da verificare','Critico']} onChange={v=>sectionField('warehouse','roofState',v)}/><QuickPorts ports={w.ports||[]} onChange={(ports)=>sectionField('warehouse','ports',ports)}/></RapidCard>

      <RapidCard n="7" title="Configurazione Mollo"><QuickChoice label="Area officina" value={ws.liveAssessment} options={['Sì','Con modifiche','No','Da verificare']} onChange={v=>{sectionField('workshop','liveAssessment',v);sectionField('workshop','workshopPossible',v==='No'?'No':v==='Da verificare'?'Da verificare':'Sì')}}/><QuickChoice label="Lavaggio" value={wash.liveAssessment} options={['Sì','Con modifiche','No','Da verificare']} onChange={v=>{sectionField('wash','liveAssessment',v);sectionField('wash','washPossible',v==='No'?'No':v==='Da verificare'?'Da verificare':'Sì')}}/><QuickChoice label="Rifornimento" value={fuel.liveAssessment} options={['Sì','Con modifiche','No','Da verificare']} onChange={v=>{sectionField('fuel','liveAssessment',v);sectionField('fuel','fuelPossible',v==='No'?'No':v==='Da verificare'?'Da verificare':'Sì')}}/><QuickChoice label="Reception / area clienti" value={o.reception} options={['Presente','Realizzabile','Non realizzabile','Da verificare']} onChange={v=>sectionField('offices','reception',v)}/><QuickChoice label="Uffici" value={o.officeAdequacy} options={['Sì','Con modifiche','No','Da verificare']} onChange={v=>sectionField('offices','officeAdequacy',v)}/></RapidCard>

      <RapidCard n="8" title="Impianti essenziali"><QuickChoice label="Trifase" value={s.threePhase} options={['Presente','Assente','Da verificare']} onChange={v=>sectionField('systems','threePhase',v)}/><QuickChoice label="Acqua" value={s.waterConnection} options={['Presente','Assente','Da verificare']} onChange={v=>sectionField('systems','waterConnection',v)}/><QuickChoice label="Scarichi" value={s.sewer} options={['Presenti','Assenti','Da verificare']} onChange={v=>sectionField('systems','sewer',v)}/><QuickChoice label="Antincendio" value={s.fireSafety} options={['Presenti','Assenti','Da verificare']} onChange={v=>sectionField('systems','fireSafety',v)}/></RapidCard>

      <RapidCard n="9" title="Foto rapide"><p className="hint">Scatta e continua. La categoria viene assegnata automaticamente.</p><div className="rapid-photo-grid">{photoButtons.map(([label,category])=><QuickPhotoButton key={label} inspectionId={inspection.id} label={label} category={category} tick={photoTick} onChanged={()=>setPhotoTick(x=>x+1)}/>)}</div><button className="btn ghost wide" onClick={()=>location.hash=`#/inspection/${id}/photos`}>Gestisci / annota foto</button></RapidCard>

      <RapidCard n="10" title="Note sopralluogo"><Area label="Note live" value={rapid.liveNotes} rows={6} placeholder="Usa anche la dettatura vocale della tastiera Android…" onChange={v=>rapidField('liveNotes',v)}/></RapidCard>

      <RapidCard n="11" title="Criticità da non dimenticare"><MultiChoice value={rapid.criticalities||[]} options={['Accesso','Piazzale','Cavi','Altezze','Urbanistica','Officina','Lavaggio','Rifornimento','Altro']} onChange={v=>rapidField('criticalities',v)}/><Area label="Nota criticità" value={rapid.criticalityNotes} onChange={v=>rapidField('criticalityNotes',v)}/></RapidCard>

      <RapidCard n="12" title="Prima impressione"><QuickChoice value={inspection.judgment||''} options={[...judgementOptions]} onChange={v=>topPatch({judgment:v as any})}/></RapidCard>

      <section className="rapid-finish"><div><strong>Completezza live {live}%</strong><span>Scheda completa {inspection.completeness??0}%</span></div><button className="btn primary big" disabled={working} onClick={pdf}>{working?'Generazione…':'Report rapido PDF'}</button><button className="btn secondary big" onClick={()=>location.hash=`#/share/${inspection.id}?type=rapid`}>Invia report rapido via email</button><button className="btn success big" onClick={()=>completeLive(false)}>Salva e chiudi</button><button className="btn ghost big" onClick={()=>completeLive(true)}>Continua scheda completa</button></section>
    </main>
    {picker&&<LocationPicker lat={inspection.lat} lng={inspection.lng} onClose={()=>setPicker(false)} onConfirm={async(lat,lng)=>{setPicker(false);const r=await reverseGeocode(lat,lng);topPatch({lat,lng,address:r?.address||inspection.address,municipality:r?.municipality||inspection.municipality,province:r?.province||inspection.province,postalCode:r?.postalCode||inspection.postalCode,name:r?.municipality&&r?.address?`${r.municipality} – ${r.address}`:inspection.name})}}/>}
  </div>
}

function RapidCard({n,title,children}:{n:string;title:string;children:any}){return <section className="card rapid-card"><div className="rapid-card-title"><span>{n}</span><h2>{title}</h2></div>{children}</section>}
function QuickChoice({label,value,options,onChange}:{label?:string;value:any;options:string[];onChange:(v:string)=>void}){return <div className="rapid-choice">{label&&<label>{label}</label>}<div className="chips">{options.map(o=><button type="button" key={o} className={`chip ${value===o?'selected':''}`} onClick={()=>onChange(o)}>{o}</button>)}</div></div>}
function MultiChoice({value,options,onChange}:{value:string[];options:string[];onChange:(v:string[])=>void}){return <div className="chips">{options.map(o=><button type="button" key={o} className={`chip ${value.includes(o)?'selected':''}`} onClick={()=>onChange(value.includes(o)?value.filter(x=>x!==o):[...value,o])}>{o}</button>)}</div>}
function Num({label,value,unit,onChange}:{label:string;value:any;unit?:string;onChange:(v:any)=>void}){return <div className="field-block"><label>{label}</label><div className="input-with-unit"><input type="number" inputMode="decimal" value={value??''} onChange={e=>onChange(e.target.value===''?'':Number(e.target.value))}/>{unit&&<span className="unit">{unit}</span>}</div></div>}
function Text({label,value,onChange}:{label:string;value:any;onChange:(v:string)=>void}){return <div className="field-block"><label>{label}</label><input value={value??''} onChange={e=>onChange(e.target.value)}/></div>}
function Area({label,value,onChange,rows=4,placeholder}:{label:string;value:any;onChange:(v:string)=>void;rows?:number;placeholder?:string}){return <div className="field-block"><label>{label}</label><textarea rows={rows} placeholder={placeholder} value={value??''} onChange={e=>onChange(e.target.value)}/></div>}
function QuickPorts({ports,onChange}:{ports:any[];onChange:(p:any[])=>void}){const add=()=>onChange([...ports,{name:`Portone ${ports.length+1}`}]);return <div className="quick-ports"><div className="card-heading"><h3>Portoni</h3><button className="btn secondary small" onClick={add}>+ Aggiungi portone</button></div>{ports.slice(1).map((p,i)=><div className="quick-port-row" key={i}><strong>{p.name||`Portone ${i+2}`}</strong><input type="number" inputMode="decimal" placeholder="Larg. m" value={p.width??''} onChange={e=>{const x=[...ports];x[i+1]={...x[i+1],width:e.target.value===''?'':Number(e.target.value)};onChange(x)}}/><input type="number" inputMode="decimal" placeholder="Alt. m" value={p.height??''} onChange={e=>{const x=[...ports];x[i+1]={...x[i+1],height:e.target.value===''?'':Number(e.target.value)};onChange(x)}}/></div>)}</div>}
function safeName(i:Inspection){return (i.municipality||i.name||'capannone').replace(/[^a-zA-Z0-9_-]+/g,'_')}

function QuickPhotoButton({inspectionId,label,category,tick,onChanged}:{inspectionId:string;label:string;category:string;tick:number;onChanged:()=>void}){const[count,setCount]=useState(0);useEffect(()=>{db.photos.where('inspectionId').equals(inspectionId).and(p=>p.category===category).count().then(setCount)},[inspectionId,category,tick]);const add=async(files:FileList|null)=>{if(!files?.[0]||count>=5)return;const f=files[0],previewBlob=await optimizeImage(f);const all=await db.photos.where('inspectionId').equals(inspectionId).toArray();await db.photos.add({id:uid(),inspectionId,category,blob:f,previewBlob,includeInReport:all.filter(p=>p.includeInReport).length<4,createdAt:nowIso()});onChanged()};return <label className="rapid-photo-btn"><span>＋</span><strong>{label}</strong><small>{count}/5</small><input hidden type="file" accept="image/*" capture="environment" onChange={e=>{add(e.target.files);e.currentTarget.value=''}}/></label>}
async function optimizeImage(file:Blob):Promise<Blob>{try{const url=URL.createObjectURL(file),img=new Image();await new Promise<void>((res,rej)=>{img.onload=()=>res();img.onerror=()=>rej();img.src=url});const max=1800,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);const ctx=c.getContext('2d');if(!ctx){URL.revokeObjectURL(url);return file}ctx.drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);return await new Promise<Blob>(resolve=>c.toBlob(b=>resolve(b||file),'image/jpeg',.82))}catch{return file}}
