import { useEffect, useState } from 'react'
import { db, nowIso, uid } from '../db'
import type { Branch, Zone } from '../types'
import { hashPin, setPinHash } from '../services/security'

const defaultWeights={access:20,yard:20,warehouse:15,configuration:20,location:15,offices:5,systemsPlanning:5}
const defaultThresholds={excellent:85,good:70,evaluable:55,critical:40}
const defaultBlocking={heavyAccess:true,useCompatible:true,rentalCompatible:true,storageCompatible:true,configuration:true,overheadPowerLines:false,workshop:false,wash:false,fuel:false}
type WeightKey=keyof typeof defaultWeights
type ThresholdKey=keyof typeof defaultThresholds
type BlockingKey=keyof typeof defaultBlocking
const weightLabels:Record<WeightKey,string>={access:'Accessibilità e viabilità',yard:'Piazzale',warehouse:'Capannone',configuration:'Configurazione filiale',location:'Posizione e zona commerciale',offices:'Uffici e servizi',systemsPlanning:'Impianti + Urbanistica'}
const thresholdLabels:Record<ThresholdKey,string>={excellent:'Ottimo da',good:'Buono da',evaluable:'Valutabile da',critical:'Critico da'}
const blockingLabels:Record<BlockingKey,string>={heavyAccess:'Accesso mezzi pesanti non possibile',useCompatible:"Destinazione d'uso incompatibile",rentalCompatible:'Attività di noleggio non compatibile',storageCompatible:'Deposito mezzi non compatibile',configuration:'Configurazione filiale non idonea',overheadPowerLines:'Cavi elettrici aerei presenti',workshop:'Area officina non realizzabile',wash:'Area lavaggio non realizzabile',fuel:'Area rifornimento non realizzabile'}
function loadSetting<T>(key:string,fallback:T):T{try{return {...fallback,...JSON.parse(localStorage.getItem(key)||'{}')} as T}catch{return fallback}}

export function SettingsPage(){const[zones,setZones]=useState<Zone[]>([]);const[branches,setBranches]=useState<Branch[]>([]);const[weights,setWeights]=useState<Record<WeightKey,number>>(()=>loadSetting('sf-weights',defaultWeights));const[thresholds,setThresholds]=useState<Record<ThresholdKey,number>>(()=>loadSetting('sf-thresholds',defaultThresholds));const[blocking,setBlocking]=useState<Record<BlockingKey,boolean>>(()=>loadSetting('sf-blocking',defaultBlocking));const[newZone,setNewZone]=useState('');const[pin,setPin]=useState('');const[pinEnabled,setPinEnabled]=useState(!!localStorage.getItem('sf-pin-hash'))
  const load=async()=>{setZones(await db.zones.toArray());setBranches(await db.branches.orderBy('name').toArray())};useEffect(()=>{load()},[])
  const saveEval=()=>{if(Object.values(weights).reduce((a:any,b:any)=>Number(a)+Number(b),0)!==100)return alert('Il totale dei pesi deve essere 100%.');localStorage.setItem('sf-weights',JSON.stringify(weights));localStorage.setItem('sf-thresholds',JSON.stringify(thresholds));localStorage.setItem('sf-blocking',JSON.stringify(blocking));alert('Parametri di valutazione salvati.')}
  const savePin=async()=>{if(pin.length<4)return alert('Usa almeno 4 cifre/caratteri.');setPinHash(await hashPin(pin));setPin('');setPinEnabled(true);alert('PIN impostato.')}
  const importBranches=async(file:File)=>{const text=await file.text();let rows:any[]=[];try{if(file.name.toLowerCase().endsWith('.json'))rows=JSON.parse(text);else{const lines=text.split(/\r?\n/).filter(Boolean);const headers=lines[0].split(';').map(x=>x.trim());rows=lines.slice(1).map(line=>{const vals=line.split(';');return Object.fromEntries(headers.map((h,i)=>[h,vals[i]?.trim()]))})}}catch{return alert('File non leggibile.')};const parsed:Branch[]=rows.map(r=>({id:r.id||uid(),name:r.name||r.nome,municipality:r.municipality||r.comune||'',province:r.province||r.provincia||'',address:r.address||r.indirizzo||'',lat:Number(r.lat||r.latitude),lng:Number(r.lng||r.lon||r.longitude)})).filter(r=>r.name&&Number.isFinite(r.lat)&&Number.isFinite(r.lng));if(!parsed.length)return alert('Nessuna filiale valida. Usa colonne name;municipality;province;address;lat;lng oppure JSON equivalente.');await db.branches.bulkPut(parsed);await load();alert(`${parsed.length} filiali importate.`)}
  return <div className="page narrow-page"><header className="topbar"><button className="back-btn" onClick={()=>history.back()}>←</button><div><div className="eyebrow">Sviluppo Filiali</div><h1>Impostazioni</h1></div></header>
    <section className="card"><h3>Sicurezza</h3><p className="muted">PIN locale per impedire accessi casuali all'app.</p><div className="inline-create"><input type="password" inputMode="numeric" placeholder={pinEnabled?'Nuovo PIN':'Imposta PIN'} value={pin} onChange={e=>setPin(e.target.value)}/><button className="btn primary" onClick={savePin}>{pinEnabled?'Modifica':'Attiva'}</button></div>{pinEnabled&&<button className="btn ghost wide" onClick={()=>{if(confirm('Disattivare il PIN?')){setPinHash('');setPinEnabled(false)}}}>Disattiva PIN</button>}</section>
    <section className="card"><div className="card-heading"><h3>Zone</h3></div><div className="inline-create"><input placeholder="Nuova zona" value={newZone} onChange={e=>setNewZone(e.target.value)}/><button className="btn secondary" onClick={async()=>{if(!newZone.trim())return;await db.zones.add({id:uid(),name:newZone.trim(),createdAt:nowIso(),updatedAt:nowIso()});setNewZone('');load()}}>+ Crea</button></div><div className="list-stack">{zones.map(z=><div className="list-row" key={z.id}><strong>{z.name}</strong><button className="icon-btn danger" onClick={async()=>{if((await db.inspections.where('zoneId').equals(z.id).count())>0)return alert('La zona contiene sopralluoghi. Spostali prima di eliminarla.');if(confirm('Eliminare zona?')){await db.zones.delete(z.id);load()}}}>×</button></div>)}</div></section>
    <section className="card"><h3>Pesi valutazione</h3>{(Object.keys(weightLabels) as WeightKey[]).map(k=><div className="setting-row" key={k}><span>{weightLabels[k]}</span><div className="input-with-unit compact"><input type="number" value={weights[k]} onChange={e=>setWeights({...weights,[k]:Number(e.target.value)})}/><span className="unit">%</span></div></div>)}<div className="total-row">Totale <b>{Object.values(weights).reduce((a,b)=>a+b,0)}%</b></div></section>
    <section className="card"><h3>Soglie punteggio</h3>{(Object.keys(thresholdLabels) as ThresholdKey[]).map(k=><div className="setting-row" key={k}><span>{thresholdLabels[k]}</span><input className="small-number" type="number" value={thresholds[k]} onChange={e=>setThresholds({...thresholds,[k]:Number(e.target.value)})}/></div>)}</section>
    <section className="card"><h3>Requisiti bloccanti</h3>{(Object.keys(blockingLabels) as BlockingKey[]).map(k=><label className="toggle-row" key={k}><span>{blockingLabels[k]}</span><input type="checkbox" checked={blocking[k]} onChange={e=>setBlocking({...blocking,[k]:e.target.checked})}/></label>)}<button className="btn primary wide" onClick={saveEval}>Salva valutazione</button></section>
    <section className="card"><h3>Foto e scheda tecnica</h3><div className="setting-row"><span>Qualità foto</span><strong>Alta / originale conservato</strong></div><div className="setting-row"><span>Foto per categoria</span><strong>5</strong></div><div className="setting-row"><span>Formato report</span><strong>A4 · 1 pagina</strong></div><div className="setting-row"><span>Foto nel report</span><strong>max 4</strong></div></section>
    <section className="card"><div className="card-heading"><div><h3>Filiali Mollo</h3><div className="muted small-text">Necessarie per calcolare la sede più vicina.</div></div><strong>{branches.length}</strong></div><label className="btn secondary wide file-btn">Importa elenco CSV / JSON<input hidden type="file" accept=".csv,.json,text/csv,application/json" onChange={e=>e.target.files?.[0]&&importBranches(e.target.files[0])}/></label><p className="hint">CSV: <code>name;municipality;province;address;lat;lng</code></p><div className="list-stack compact-list">{branches.slice(0,8).map(b=><div className="list-row" key={b.id}><div><strong>{b.name}</strong><span className="muted small-text">{b.municipality}</span></div><button className="icon-btn danger" onClick={async()=>{await db.branches.delete(b.id);load()}}>×</button></div>)}{branches.length>8&&<div className="muted">+ altre {branches.length-8}</div>}</div></section>
    <section className="card danger-zone"><h3>Ripristino e dati</h3><button className="btn secondary wide" onClick={()=>{localStorage.setItem('sf-weights',JSON.stringify(defaultWeights));localStorage.setItem('sf-thresholds',JSON.stringify(defaultThresholds));localStorage.setItem('sf-blocking',JSON.stringify(defaultBlocking));location.reload()}}>Ripristina impostazioni predefinite</button><button className="btn danger wide" onClick={async()=>{if(confirm('Eliminare TUTTI i dati locali? Questa operazione non è reversibile.')){await db.delete();location.reload()}}}>Elimina tutti i dati</button></section>
  </div>}
