import { useEffect, useMemo, useState } from 'react'
import { db, nowIso, uid } from '../db'
import type { DocumentRecord, Inspection, PhotoRecord, Zone } from '../types'
import { generateFullReportPdf, generateRapidReportPdf, generateReportPdf } from '../services/report'
import { googleMapsUrl, nearestBranch } from '../services/geo'
import { downloadBlob } from '../services/backup'
import { rapidCompleteness } from '../services/rapid'

type ReportType='rapid'|'summary'|'full'

export function SharePage({id}:{id:string}){
  const[i,setI]=useState<Inspection>();const[z,setZ]=useState<Zone>();const[docs,setDocs]=useState<DocumentRecord[]>([]);const[photos,setPhotos]=useState<PhotoRecord[]>([]);const[selectedDocs,setSelectedDocs]=useState<string[]>([]);const[includePhotos,setIncludePhotos]=useState(false);const[subject,setSubject]=useState('');const[body,setBody]=useState('');const[working,setWorking]=useState(false);const[type,setType]=useState<ReportType>(()=>{const v=new URLSearchParams(location.hash.split('?')[1]||'').get('type');return v==='rapid'||v==='full'||v==='summary'?v:'summary'})
  useEffect(()=>{(async()=>{const x=await db.inspections.get(id);if(!x)return;setI(x);const zone=await db.zones.get(x.zoneId);setZ(zone);setDocs(await db.documents.where('inspectionId').equals(id).toArray());setPhotos((await db.photos.where('inspectionId').equals(id).toArray()).filter(p=>p.includeInReport))})()},[id])
  useEffect(()=>{if(!i)return;(async()=>{const branches=await db.branches.toArray(),nb=nearestBranch(i.lat,i.lng,branches),d=i.data||{},g=d.general||{},w=d.warehouse||{},y=d.yard||{},o=d.offices||{},a=d.access||{},r=d.rapid||{};const prefix=type==='rapid'?'Sopralluogo rapido':type==='full'?'Report completo':'Sopralluogo capannone';setSubject(`${prefix} – ${z?.name||'Zona'} – ${i.address||i.name}`);const common=[`Data sopralluogo: ${new Date(i.date).toLocaleDateString('it-IT')}`,`Zona: ${z?.name||'—'}`,`Indirizzo: ${i.address||'—'}`,`Superficie coperta: ${w.coveredArea||g.declaredCoveredArea||'—'} m²`,`Piazzale: ${y.yardArea||g.declaredYardArea||'—'} m²`,`Uffici: ${o.officeArea||'—'} m²`,`Operazione: ${g.availabilityType||'—'}`,g.rent?`Canone: € ${Number(g.rent).toLocaleString('it-IT')}/mese`:'',g.salePrice?`Prezzo: € ${Number(g.salePrice).toLocaleString('it-IT')}`:'',`Accesso bilici: ${a.semiAccess||'—'}`,nb?`Filiale Mollo più vicina: ${nb.branch.name} – ${nb.distanceKm.toFixed(1)} km`:''];if(type==='rapid')common.push(`Completezza live: ${rapidCompleteness(i)}%`,`Prima impressione: ${i.judgment||'—'}`,r.criticalities?.length?`Criticità live: ${r.criticalities.join('; ')}`:'',r.liveNotes?`Note: ${r.liveNotes}`:'');else common.push(`Punteggio: ${i.score??'—'}/100`,`Giudizio personale: ${i.judgment||'—'}`,i.blockingIssues?.length?`Criticità bloccanti: ${i.blockingIssues.join('; ')}`:'',d.evaluation?.finalNotes?`Considerazioni: ${d.evaluation.finalNotes}`:'');common.push(`Google Maps: ${googleMapsUrl(i.lat,i.lng,i.address)}`);setBody(common.filter(Boolean).join('\n'))})()},[i,z,type])
  const extraSize=useMemo(()=>docs.filter(d=>selectedDocs.includes(d.id)).reduce((s,d)=>s+d.blob.size,0)+(includePhotos?photos.reduce((s,p)=>s+(p.editedBlob||p.previewBlob||p.blob).size,0):0),[docs,selectedDocs,includePhotos,photos])
  if(!i)return <div className="loading">Caricamento...</div>
  const makePdf=()=>type==='rapid'?generateRapidReportPdf(i,z):type==='full'?generateFullReportPdf(i,z):generateReportPdf(i,z)
  const filename=()=>`${type==='rapid'?'Sopralluogo_Rapido':type==='full'?'Report_Completo':'Scheda_Tecnica'}_${(i.municipality||'capannone').replace(/[^a-zA-Z0-9_-]+/g,'_')}_${i.date}.pdf`
  const share=async()=>{setWorking(true);try{const pdf=await makePdf();const files:File[]=[new File([pdf],filename(),{type:'application/pdf'})];docs.filter(d=>selectedDocs.includes(d.id)).forEach(d=>files.push(new File([d.blob],d.name,{type:d.mimeType||d.blob.type})));if(includePhotos)photos.forEach((p,n)=>{const b=p.editedBlob||p.previewBlob||p.blob;files.push(new File([b],`foto_report_${n+1}.${b.type.includes('png')?'png':'jpg'}`,{type:b.type||'image/jpeg'}))});if(navigator.share){const data:any={title:subject,text:body};if(navigator.canShare?.({files}))data.files=files;await navigator.share(data);await db.shares.add({id:uid(),inspectionId:i.id,type:`${type} + ${files.length-1} allegati`,createdAt:nowIso()})}else{downloadBlob(pdf,files[0].name);location.href=`mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`}}catch(e:any){if(e?.name!=='AbortError')alert(e.message||'Condivisione non riuscita')}finally{setWorking(false)}}
  const pdf=async()=>{setWorking(true);try{downloadBlob(await makePdf(),filename())}finally{setWorking(false)}}
  return <div className="page narrow-page"><header className="topbar"><button className="back-btn" onClick={()=>history.back()}>←</button><div><div className="eyebrow">Condivisione</div><h1>{i.name}</h1></div></header>
    <section className="card"><h3>Tipo di report</h3><div className="report-type-grid"><button className={type==='rapid'?'active':''} onClick={()=>setType('rapid')}><strong>Rapido</strong><small>1 pagina · dati live</small></button><button className={type==='summary'?'active':''} onClick={()=>setType('summary')}><strong>Sintetico</strong><small>1 pagina · valutazione finale</small></button><button className={type==='full'?'active':''} onClick={()=>setType('full')}><strong>Completo</strong><small>tutti i campi · multipagina</small></button></div></section>
    <section className="card"><div className="field-block"><label>Oggetto email</label><input value={subject} onChange={e=>setSubject(e.target.value)}/></div><div className="field-block"><label>Riepilogo</label><textarea rows={16} value={body} onChange={e=>setBody(e.target.value)}/></div></section>
    <section className="card"><h3>Allegati aggiuntivi</h3>{docs.map(d=><label className="toggle-row" key={d.id}><span>{d.name}<small className="muted">{d.category}</small></span><input type="checkbox" checked={selectedDocs.includes(d.id)} onChange={e=>setSelectedDocs(e.target.checked?[...selectedDocs,d.id]:selectedDocs.filter(x=>x!==d.id))}/></label>)}{photos.length>0&&<label className="toggle-row"><span>Foto selezionate per report ({photos.length})</span><input type="checkbox" checked={includePhotos} onChange={e=>setIncludePhotos(e.target.checked)}/></label>}<div className="hint">Allegati extra: {(extraSize/1024/1024).toFixed(1)} MB. Il PDF scelto viene aggiunto sempre.</div></section>
    <section className="card"><h3>Azioni</h3><div className="stack-buttons"><button className="btn primary big" disabled={working} onClick={share}>{working?'Preparazione…':'Invia / condividi via email'}</button><button className="btn secondary" disabled={working} onClick={pdf}>Salva solo PDF</button><button className="btn ghost" onClick={()=>window.open(googleMapsUrl(i.lat,i.lng,i.address),'_blank')}>Apri posizione Google Maps</button></div></section></div>}
