import { useEffect, useMemo, useState } from 'react'
import { db, nowIso, uid } from '../db'
import type { DocumentRecord, Inspection, PhotoRecord, Zone } from '../types'
import { generateReportPdf } from '../services/report'
import { googleMapsUrl, nearestBranch } from '../services/geo'
import { downloadBlob } from '../services/backup'

export function SharePage({id}:{id:string}){const[i,setI]=useState<Inspection>();const[z,setZ]=useState<Zone>();const[docs,setDocs]=useState<DocumentRecord[]>([]);const[photos,setPhotos]=useState<PhotoRecord[]>([]);const[selectedDocs,setSelectedDocs]=useState<string[]>([]);const[includePhotos,setIncludePhotos]=useState(false);const[subject,setSubject]=useState('');const[body,setBody]=useState('');const[working,setWorking]=useState(false)
  useEffect(()=>{(async()=>{const x=await db.inspections.get(id);if(!x)return;setI(x);const zone=await db.zones.get(x.zoneId);setZ(zone);setDocs(await db.documents.where('inspectionId').equals(id).toArray());setPhotos((await db.photos.where('inspectionId').equals(id).toArray()).filter(p=>p.includeInReport));const branches=await db.branches.toArray();const nb=nearestBranch(x.lat,x.lng,branches);setSubject(`Sopralluogo capannone – ${zone?.name||'Zona'} – ${x.address||x.name}`);const d=x.data||{},g=d.general||{},w=d.warehouse||{},y=d.yard||{};setBody([`Data sopralluogo: ${new Date(x.date).toLocaleDateString('it-IT')}`,`Zona: ${zone?.name||'—'}`,`Indirizzo: ${x.address||'—'}`,`Superficie coperta: ${w.coveredArea||g.declaredCoveredArea||'—'} m²`,`Piazzale: ${y.yardArea||g.declaredYardArea||'—'} m²`,`Piazzale realmente utilizzabile: ${y.usableYardArea||'—'} m²`,`Operazione: ${g.availabilityType||'—'}`,g.rent?`Canone: € ${Number(g.rent).toLocaleString('it-IT')}/mese`:'',g.salePrice?`Prezzo: € ${Number(g.salePrice).toLocaleString('it-IT')}`:'',`Punteggio: ${x.score??'—'}/100`,`Giudizio personale: ${x.judgment||'—'}`,nb?`Filiale Mollo più vicina: ${nb.branch.name} – ${nb.distanceKm.toFixed(1)} km`:'',x.strengths?.length?`Punti di forza: ${x.strengths.join('; ')}`:'',x.issues?.length?`Criticità: ${x.issues.join('; ')}`:'',d.evaluation?.finalNotes?`Considerazioni: ${d.evaluation.finalNotes}`:'',`Google Maps: ${googleMapsUrl(x.lat,x.lng,x.address)}`].filter(Boolean).join('\n'))})()},[id])
  const extraSize=useMemo(()=>docs.filter(d=>selectedDocs.includes(d.id)).reduce((s,d)=>s+d.blob.size,0)+(includePhotos?photos.reduce((s,p)=>s+(p.editedBlob||p.previewBlob||p.blob).size,0):0),[docs,selectedDocs,includePhotos,photos])
  if(!i)return <div className="loading">Caricamento...</div>
  const share=async()=>{setWorking(true);try{const pdf=await generateReportPdf(i,z);const files:File[]=[new File([pdf],`SviluppoFiliali_${(i.municipality||'capannone').replaceAll(' ','_')}_${i.date}.pdf`,{type:'application/pdf'})];docs.filter(d=>selectedDocs.includes(d.id)).forEach(d=>files.push(new File([d.blob],d.name,{type:d.mimeType||d.blob.type})));if(includePhotos)photos.forEach((p,n)=>{const b=p.editedBlob||p.previewBlob||p.blob;files.push(new File([b],`foto_report_${n+1}.${b.type.includes('png')?'png':'jpg'}`,{type:b.type||'image/jpeg'}))});if(navigator.share){const data:any={title:subject,text:body};if(navigator.canShare?.({files}))data.files=files;await navigator.share(data);await db.shares.add({id:uid(),inspectionId:i.id,type:`PDF + riepilogo + ${files.length-1} allegati`,createdAt:nowIso()})}else{downloadBlob(pdf,files[0].name);location.href=`mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`}}catch(e:any){if(e?.name!=='AbortError')alert(e.message||'Condivisione non riuscita')}finally{setWorking(false)}}
  const pdf=async()=>{const b=await generateReportPdf(i,z);downloadBlob(b,`SviluppoFiliali_${i.municipality}_${i.date}.pdf`)}
  return <div className="page narrow-page"><header className="topbar"><button className="back-btn" onClick={()=>history.back()}>←</button><div><div className="eyebrow">Condivisione</div><h1>{i.name}</h1></div></header><section className="card"><div className="field-block"><label>Oggetto email</label><input value={subject} onChange={e=>setSubject(e.target.value)}/></div><div className="field-block"><label>Riepilogo</label><textarea rows={16} value={body} onChange={e=>setBody(e.target.value)}/></div></section><section className="card"><h3>Allegati aggiuntivi</h3>{docs.map(d=><label className="toggle-row" key={d.id}><span>{d.name}<small className="muted">{d.category}</small></span><input type="checkbox" checked={selectedDocs.includes(d.id)} onChange={e=>setSelectedDocs(e.target.checked?[...selectedDocs,d.id]:selectedDocs.filter(x=>x!==d.id))}/></label>)}{photos.length>0&&<label className="toggle-row"><span>Foto selezionate per report ({photos.length})</span><input type="checkbox" checked={includePhotos} onChange={e=>setIncludePhotos(e.target.checked)}/></label>}<div className="hint">Allegati extra selezionati: {(extraSize/1024/1024).toFixed(1)} MB. Il PDF viene aggiunto sempre.</div></section><section className="card"><h3>Azioni</h3><div className="stack-buttons"><button className="btn primary big" disabled={working} onClick={share}>{working?'Preparazione…':'Condividi PDF + riepilogo'}</button><button className="btn secondary" onClick={pdf}>Salva solo PDF</button><button className="btn ghost" onClick={()=>window.open(googleMapsUrl(i.lat,i.lng,i.address),'_blank')}>Apri posizione Google Maps</button></div></section></div>}
